/*
 * Ghost4J: a Java wrapper for Ghostscript API.
 *
 * Distributable under LGPL license.
 * See terms of license at http://www.gnu.org/licenses/lgpl.html.
 */

package org.ghost4j.analyzer;

import java.io.Serializable;

/**
 * Interface defining an analysis item: a piece of data generated by an
 * Analyser.
 * 
 * @author Gilles Grousset (gi.grousset@gmail.com)
 */
public interface AnalysisItem extends Serializable {

}
